//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarroResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarroResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.CarroResource", typeof(CarroResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carro foi alterado com sucesso..
        /// </summary>
        public static string Carro_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Carro_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carro foi cadastrado com sucesso..
        /// </summary>
        public static string Carro_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Carro_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carro com o ID informado foi encontrado com sucesso..
        /// </summary>
        public static string Carro_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Carro_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carro foi excluído com sucesso..
        /// </summary>
        public static string Carro_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Carro_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória e não foi informada..
        /// </summary>
        public static string Descricao_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Descricao_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carro com o ID informado não existe..
        /// </summary>
        public static string Id_Carro_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Carro_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do proprietário é obrigatório e não foi informado..
        /// </summary>
        public static string Id_Proprietario_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Proprietario_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do usuário responsável pela procura é inválido..
        /// </summary>
        public static string Id_Usuario_Procura_Invalido {
            get {
                return ResourceManager.GetString("Id_Usuario_Procura_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil do usuário responsável pela procura é obrigatório e não foi informado..
        /// </summary>
        public static string Perfil_Usuario_Procura_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Perfil_Usuario_Procura_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da placa é obrigatório e não foi informado..
        /// </summary>
        public static string Placa_Obrigatoria_Nao_Informado {
            get {
                return ResourceManager.GetString("Placa_Obrigatoria_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de lugares informada é inválida..
        /// </summary>
        public static string Quantidade_Lugares_Invalida {
            get {
                return ResourceManager.GetString("Quantidade_Lugares_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui perfil de acesso para alterar as informações desse carro..
        /// </summary>
        public static string Usuario_Sem_Perfil_Acesso_Alterar_Informacao {
            get {
                return ResourceManager.GetString("Usuario_Sem_Perfil_Acesso_Alterar_Informacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui perfil de acesso para excluir esse carro..
        /// </summary>
        public static string Usuario_Sem_Perfil_Acesso_Excluir_Informacao {
            get {
                return ResourceManager.GetString("Usuario_Sem_Perfil_Acesso_Excluir_Informacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui perfil de acesso para obter as informações desse carro..
        /// </summary>
        public static string Usuario_Sem_Perfil_Acesso_Obter_Informacao {
            get {
                return ResourceManager.GetString("Usuario_Sem_Perfil_Acesso_Obter_Informacao", resourceCulture);
            }
        }
    }
}
