//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalidadeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalidadeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.LocalidadeResource", typeof(LocalidadeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade com o ID informado não existe..
        /// </summary>
        public static string Id_Localidade_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Localidade_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade foi alterada com sucesso..
        /// </summary>
        public static string Localidade_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Localidade_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade foi cadastrada com sucesso..
        /// </summary>
        public static string Localidade_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Localidade_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade com o ID informado foi encontrada com sucesso..
        /// </summary>
        public static string Localidade_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Localidade_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade foi excluída com sucesso..
        /// </summary>
        public static string Localidade_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Localidade_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma localidade cadastrada com o nome e estado informados..
        /// </summary>
        public static string Localidade_Ja_Existe_Por_Nome_Uf {
            get {
                return ResourceManager.GetString("Localidade_Ja_Existe_Por_Nome_Uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma localidade que esteja associada a pelo menos uma viagem cadastrada. Exclua todas as viagens associadas a localidade antes de excluí-la..
        /// </summary>
        public static string Nao_Possivel_Excluir_Localidade_Com_Viagens {
            get {
                return ResourceManager.GetString("Nao_Possivel_Excluir_Localidade_Com_Viagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da localidade é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A silga da localidade é obrigatória e não foi informada..
        /// </summary>
        public static string Sigla_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Sigla_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado da localidade é obrigatório e não foi informado..
        /// </summary>
        public static string Uf_Obrigatoria_Nao_Informado {
            get {
                return ResourceManager.GetString("Uf_Obrigatoria_Nao_Informado", resourceCulture);
            }
        }
    }
}
