//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MotoristaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MotoristaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.MotoristaResource", typeof(MotoristaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da CNH é obrigatório e não foi informado..
        /// </summary>
        public static string Cnh_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Cnh_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motorista com o ID informado não existe..
        /// </summary>
        public static string Id_Motorista_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Motorista_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motorista foi alterado com sucesso..
        /// </summary>
        public static string Motorista_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Motorista_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motorista foi cadastrado com sucesso..
        /// </summary>
        public static string Motorista_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Motorista_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motorista com o ID informado foi encontrado com sucesso..
        /// </summary>
        public static string Motorista_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Motorista_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motorista foi excluído com sucesso..
        /// </summary>
        public static string Motorista_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Motorista_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um motorista que esteja associado a pelo menos uma viagem cadastrada. Exclua todas as viagens associadas ao motorista antes de excluí-lo..
        /// </summary>
        public static string Nao_Possivel_Excluir_Motorista_Com_Viagens {
            get {
                return ResourceManager.GetString("Nao_Possivel_Excluir_Motorista_Com_Viagens", resourceCulture);
            }
        }
    }
}
