//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProprietarioCarroResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProprietarioCarroResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.ProprietarioCarroResource", typeof(ProprietarioCarroResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O proprietário com o ID informado não existe..
        /// </summary>
        public static string Id_Proprietario_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Proprietario_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um proprietário que possua carros cadastradas. Exclua todos os carros do proprietário antes de excluí-lo..
        /// </summary>
        public static string Nao_Possivel_Excluir_Proprietario_Com_Carros {
            get {
                return ResourceManager.GetString("Nao_Possivel_Excluir_Proprietario_Com_Carros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O proprietário foi alterado com sucesso..
        /// </summary>
        public static string Proprietario_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Proprietario_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O proprietário foi cadastrado com sucesso..
        /// </summary>
        public static string Proprietario_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Proprietario_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O proprietário com o ID informado foi encontrado com sucesso..
        /// </summary>
        public static string Proprietario_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Proprietario_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O proprietário foi excluído com sucesso..
        /// </summary>
        public static string Proprietario_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Proprietario_Excluido_Com_Sucesso", resourceCulture);
            }
        }
    }
}
