//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReservaDependenteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservaDependenteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.ReservaDependenteResource", typeof(ReservaDependenteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento é obrigatória e não foi informada..
        /// </summary>
        public static string Data_Nascimento_Obrigatoria_Nao_Informado {
            get {
                return ResourceManager.GetString("Data_Nascimento_Obrigatoria_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dependente foi alterado com sucesso..
        /// </summary>
        public static string Dependente_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Dependente_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dependente foi cadastrado com sucesso..
        /// </summary>
        public static string Dependente_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Dependente_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dependente da reserva com o ID informado foi encontrado com sucesso..
        /// </summary>
        public static string Dependente_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Dependente_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dependente foi excluído com sucesso..
        /// </summary>
        public static string Dependente_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Dependente_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe dependente para a reserva com o ID informado..
        /// </summary>
        public static string Dependente_Nao_Existe {
            get {
                return ResourceManager.GetString("Dependente_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo resolução da ANTT, a idade máxima permitida para um dependente é de 6 anos. Pela a data de nascimento informada, o dependente possui idade superior a esse valor..
        /// </summary>
        public static string Idade_Maxima_Superior_6_Anos {
            get {
                return ResourceManager.GetString("Idade_Maxima_Superior_6_Anos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reserva já possui um dependente. Somente um dependente é permitido por reserva..
        /// </summary>
        public static string Somente_Um_Dependente_Permitido_Por_Reserva {
            get {
                return ResourceManager.GetString("Somente_Um_Dependente_Permitido_Por_Reserva", resourceCulture);
            }
        }
    }
}
