//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do celular é obrigatório e não foi informado..
        /// </summary>
        public static string Celular_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Celular_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do CPF informado é inválido. Corrija o número informado..
        /// </summary>
        public static string Cpf_Invalido {
            get {
                return ResourceManager.GetString("Cpf_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do CPF é obrigatório e não foi informado..
        /// </summary>
        public static string Cpf_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Cpf_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado é inválido..
        /// </summary>
        public static string Email_Invalido {
            get {
                return ResourceManager.GetString("Email_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório e não foi informado..
        /// </summary>
        public static string Email_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Email_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil de acesso é obrigatório e não foi informado..
        /// </summary>
        public static string Perfil_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Perfil_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do RG é obrigatório e não foi informado..
        /// </summary>
        public static string Rg_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Rg_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso porém ocorreu um erro ao tentar enviar a senha para seu e-mail..
        /// </summary>
        public static string Senha_Alterada_Com_Erro_Envio_Email {
            get {
                return ResourceManager.GetString("Senha_Alterada_Com_Erro_Envio_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso..
        /// </summary>
        public static string Senha_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Senha_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual é obrigatória e não foi informada..
        /// </summary>
        public static string Senha_Atual_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Senha_Atual_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e a confirmação da senha são diferentes. Verifique as senhas informadas..
        /// </summary>
        public static string Senha_Confirmacao_senha_diferentes {
            get {
                return ResourceManager.GetString("Senha_Confirmacao_senha_diferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha é obrigatória e não foi informada..
        /// </summary>
        public static string Senha_Nova_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Senha_Nova_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória e não foi informada..
        /// </summary>
        public static string Senha_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Senha_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário autenticado com sucesso..
        /// </summary>
        public static string Usuario_Autenticado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Usuario_Autenticado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo. Não é possível acessar o sistema..
        /// </summary>
        public static string Usuario_Inativo {
            get {
                return ResourceManager.GetString("Usuario_Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado. Por favor verifique o login e senha informados..
        /// </summary>
        public static string Usuario_Nao_Encontrado_Por_Login_Senha {
            get {
                return ResourceManager.GetString("Usuario_Nao_Encontrado_Por_Login_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual inválida. Por favor verifique se a senha atual informada está correta..
        /// </summary>
        public static string Usuario_Nao_Encontrado_Por_Senha {
            get {
                return ResourceManager.GetString("Usuario_Nao_Encontrado_Por_Senha", resourceCulture);
            }
        }
    }
}
