//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViagemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViagemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2.Dominio.Resources.ViagemResource", typeof(ViagemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data e horário da saída são obrigatórios e não foram informados..
        /// </summary>
        public static string Data_Horario_Saida_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Data_Horario_Saida_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória e não foi informada..
        /// </summary>
        public static string Descricao_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Descricao_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do carro é obrigatório e não foi informado..
        /// </summary>
        public static string Id_Carro_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Carro_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do motorista é obrigatório e não foi informado..
        /// </summary>
        public static string Id_Motorista_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Motorista_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viagem com o ID informado não existe..
        /// </summary>
        public static string Id_Viagem_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Viagem_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade de desembarque com o ID informado não existe..
        /// </summary>
        public static string Localidade_Desembarque_Nao_Existe {
            get {
                return ResourceManager.GetString("Localidade_Desembarque_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A localidade de embarque com o ID informado não existe..
        /// </summary>
        public static string Localidade_Embarque_Nao_Existe {
            get {
                return ResourceManager.GetString("Localidade_Embarque_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não é o motorista escalado para a viagem, logo não é possível visualzar as informações da mesma..
        /// </summary>
        public static string Motorista_Sem_Permissao_Obter {
            get {
                return ResourceManager.GetString("Motorista_Sem_Permissao_Obter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma viagem que possua pelo menos uma reserva cadastrada. Exclua todas as reservas da viagem antes de excluí-la..
        /// </summary>
        public static string Nao_Possivel_Excluir_Viagem_Com_Reservas {
            get {
                return ResourceManager.GetString("Nao_Possivel_Excluir_Viagem_Com_Reservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não é o proprietário do carro escalado para a viagem, logo não é possível visualzar as informações da mesma..
        /// </summary>
        public static string Proprietario_Sem_Permissao_Obter {
            get {
                return ResourceManager.GetString("Proprietario_Sem_Permissao_Obter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui perfil de acesso para obter as informações dessa viagem..
        /// </summary>
        public static string Usuario_Sem_Perfil_Acesso_Obter_Informacao {
            get {
                return ResourceManager.GetString("Usuario_Sem_Perfil_Acesso_Obter_Informacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da passagem é obrigatório e não foi informado..
        /// </summary>
        public static string Valor_Passagem_Obrigatorio_Nao_Informada {
            get {
                return ResourceManager.GetString("Valor_Passagem_Obrigatorio_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viagem foi alterada com sucesso..
        /// </summary>
        public static string Viagem_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Viagem_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viagem foi cadastrada com sucesso..
        /// </summary>
        public static string Viagem_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Viagem_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viagem com o ID informado foi encontrada com sucesso..
        /// </summary>
        public static string Viagem_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Viagem_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viagem foi excluída com sucesso..
        /// </summary>
        public static string Viagem_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Viagem_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma viagem cadastrada para esse carro na data de saída informada..
        /// </summary>
        public static string Viagem_Ja_Existe_Para_Carro_Data_Saida {
            get {
                return ResourceManager.GetString("Viagem_Ja_Existe_Para_Carro_Data_Saida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma viagem cadastrada para esse motorista na data de saída informada..
        /// </summary>
        public static string Viagem_Ja_Existe_Para_Motorista_Data_Saida {
            get {
                return ResourceManager.GetString("Viagem_Ja_Existe_Para_Motorista_Data_Saida", resourceCulture);
            }
        }
    }
}
